NAME_FIELD_WEIGHT = 3.0
DESCRIPTION_FIELD_WEIGHT = 1.0
BRAND_FIELD_WEIGHT = 0.5

LEXICAL_WEIGHT = 0.7
SEMANTIC_WEIGHT = 0.3

SEMANTIC_MODEL_NAME = "all-MiniLM-L6-v2"
EMBEDDING_BATCH_SIZE = 32

DEFAULT_RESULT_LIMIT = 10
MIN_RESULT_LIMIT = 1
MAX_RESULT_LIMIT = 50

MIN_TOP_SCORE = 0.20
